ProjectIndie/config/routes.rb
Rails.application.routes.draw do
  resources :statuses

  resources :appointments

  resources :time_slots

  resources :patients

  resources :insurances

  resources :diagnostics

  resources :dermatologists

  get 'welcome/index'

   root 'welcome#index'

end

ProjectIndie/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :dermatologist
  belongs_to :patient
  belongs_to :time_slot
  belongs_to :diagnostic
  belongs_to :status

end

ProjectIndie/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  def cancelAppointment
    cancel = Appointment.cancelAppointment(params[:appointment_id])
    render json: cancel
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :time_slot_id, :diagnostic_id, :patient_id, :dermatologist_id, :reason)
    end
end

ProjectIndie/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

ProjectIndie/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :time_slot_id %><br>
    <%= f.collection_select :time_slot_id, TimeSlot.order(:Time),:id,:Time, include_blank: true, :prompt => "Choose Time" %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_id %><br>
    <%= f.collection_select :diagnostic_id, Diagnostic.order(:detail),:id,:detail, include_blank: true, :prompt => "Choose One" %>
    </div>
  <div class="field">
    <%= f.label :patient_id %><br>

    <%= f.collection_select :patient_id, Patient.order(:first_name),:id,:first_name, include_blank: true, :prompt => "Choose One" %>
  </div>
  <div class="field">
    <%= f.label :dermatologist_id %><br>

    <%= f.collection_select :dermatologist_id, Dermatologist.order(:Last_name),:id,:Last_name, include_blank: true, :prompt => "Choose One" %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ProjectIndie/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

ProjectIndie/app/views/appointments/index.html.erb
<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time Slot</th>
      <th>Diagnostic</th>
      <th>Patient</th>
      <th>Dermatologist</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>

        <td><%= appointment.date %></td>
        <td><%= appointment.time_slot.Time %></td>
        <td><%= appointment.diagnostic.code %></td>
        <td><%= appointment.patient.first_name %></td>
        <td><%= appointment.dermatologist.Last_name %></td>
        <td><%= appointment.reason %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>
<%= link_to 'Back', welcome_index_path %>

ProjectIndie/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

ProjectIndie/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Time slot:</strong>
  <%= @appointment.time_slot_id %>
</p>

<p>
  <strong>Diagnostic:</strong>
  <%= @appointment.diagnostic_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.first_name %>
</p>

<p>
  <strong>Dermatologist:</strong>
  <%= @appointment.dermatologist.Last_name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>